import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google';
import Hero from '../components/Hero';
import Services from '../components/Services';
import CompAdvantages from '../components/CompAdvantages';
import Icons from '../components/Icons';
import BuyingAdvantages from '../components/BuyingAdvantages';
import Footer from '../components/Footer';
import ProjectsReady from '../components/ProjectsReady';
import ProjectsOnGoing from '../components/ProjectsOnGoing';
import Nav from '../components/Nav';
import React, {useState} from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    //копируется номер и показывается сообщение
	const [ isAlertVisible, setIsAlertVisible ] = useState(false);

	const handleButtonNumberClick = () => {
		navigator.clipboard.writeText('+7 (937) 461-08-88');
		setTimeout(() => {
	        setIsAlertVisible(false);
		}, 1000);
		setIsAlertVisible(true);
	}
    //копируется номер и показывается сообщение

    return (
        <>
            <Head>
                <title>Строительная компания ЛИГА</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav 
                handleButtonNumberClick={handleButtonNumberClick}
                isAlertVisible={isAlertVisible}
            />
            <Hero />
            <Services />
            <CompAdvantages />
            <Icons />
            <BuyingAdvantages />
            <ProjectsReady />
            <ProjectsOnGoing />
            <Footer 
                handleButtonNumberClick={handleButtonNumberClick}
                isAlertVisible={isAlertVisible}
            />
        </>
    )
}
