import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google';
import Hero from '../components/Hero';
import Services from '../components/Services';
import CompAdvantages from '../components/CompAdvantages';
import Icons from '../components/Icons';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Строительная компания</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Services />
            <CompAdvantages />
            <Icons />
        </>
    )
}
