import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google';
import Hero from '../components/Hero';
import Services from '../components/Services';
import CompAdvantages from '../components/CompAdvantages';
import Icons from '../components/Icons';
import BuyingAdvantages from '../components/BuyingAdvantages';
import Footer from '../components/Footer';
import ProjectsReady from '../components/ProjectsReady';
import ProjectsOnGoing from '../components/ProjectsOnGoing';
import Certificates from '../components/Certificates';
import Navigation2 from '../components/Navigation2';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Строительная компания ЛИГА</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation2 />
            <Hero />
            <Services />
            <CompAdvantages />
            <Icons />
            <BuyingAdvantages />
            <ProjectsReady />
            <ProjectsOnGoing />
            {/* <Certificates /> */}
            <Footer />
        </>
    )
}
